"""initial schema

Revision ID: 59e49f2ddeda
Revises:
Create Date: 2026-09-15 15:56:13.155421

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "59e49f2ddeda"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credentials",
        sa.Column(
            "kind",
            sa.Enum(
                "PASSWORD", "TOTP_SECRET", "API_TOKEN", "SESSION_IMPORT", name="credentialkind"
            ),
            nullable=False,
        ),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("wrapped_data_key", sa.LargeBinary(), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=100), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(length=100), nullable=True),
        sa.Column("plan", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("clerk_user_id", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "role", sa.Enum("OWNER", "ADMIN", "MEMBER", "VIEWER", name="orgrole"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_clerk_user_id"), "users", ["clerk_user_id"], unique=True)
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "targets",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("root_domain", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("is_production", sa.Boolean(), nullable=False),
        sa.Column("ownership_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "ownership_verification_method",
            sa.Enum("DNS_TXT", "WELL_KNOWN_FILE", "META_TAG", name="ownershipverificationmethod"),
            nullable=True,
        ),
        sa.Column("ownership_verification_token", sa.String(length=200), nullable=True),
        sa.Column("ownership_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("authorization_accepted", sa.Boolean(), nullable=False),
        sa.Column("authorization_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("authorization_accepted_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["authorization_accepted_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_targets_organization_id"), "targets", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_targets_root_domain"), "targets", ["root_domain"], unique=False)
    op.create_table(
        "personas",
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("role_name", sa.String(length=100), nullable=False),
        sa.Column("trust_rank", sa.Integer(), nullable=False),
        sa.Column("tenant_key", sa.String(length=200), nullable=True),
        sa.Column("credential_id", sa.UUID(), nullable=True),
        sa.Column(
            "login_strategy",
            sa.Enum(
                "FORM",
                "OAUTH_REDIRECT",
                "SAML",
                "API_TOKEN",
                "HAR_REPLAY",
                "MANUAL_SESSION",
                name="loginstrategy",
            ),
            nullable=True,
        ),
        sa.Column("login_recipe", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("login_recipe_version", sa.Integer(), nullable=False),
        sa.Column("session_state_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("session_state_updated_at", sa.DateTime(), nullable=True),
        sa.Column("session_state_expires_at", sa.DateTime(), nullable=True),
        sa.Column("session_oracle", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("canary_tokens", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected_denied", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("unavailable_reason", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["credentials.id"],
        ),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_personas_target_id"), "personas", ["target_id"], unique=False)
    op.create_index(op.f("ix_personas_tenant_key"), "personas", ["tenant_key"], unique=False)
    op.create_table(
        "scan_policies",
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column(
            "intensity",
            sa.Enum("LIGHT", "STANDARD", "THOROUGH", name="scanintensity"),
            nullable=False,
        ),
        sa.Column("schedule_cron", sa.String(length=100), nullable=True),
        sa.Column("read_write_enabled", sa.Boolean(), nullable=False),
        sa.Column("max_requests_per_second", sa.Float(), nullable=False),
        sa.Column("testing_window_start_hour_utc", sa.Integer(), nullable=True),
        sa.Column("testing_window_end_hour_utc", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scan_policies_target_id"), "scan_policies", ["target_id"], unique=True)
    op.create_table(
        "scans",
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("triggered_by", sa.String(length=50), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "QUEUED",
                "SCOPE_VERIFYING",
                "BLOCKED_UNVERIFIED",
                "RECON",
                "AUTH_ESTABLISHING",
                "FAILED_AUTH",
                "CRAWLING",
                "SURFACE_MAPPING",
                "PASSIVE_CHECKS",
                "TESTING",
                "VERIFYING",
                "TRIAGING",
                "REPORTING",
                "COMPLETE",
                "PAUSED",
                "CANCELLED",
                "FAILED",
                name="scanstate",
            ),
            nullable=False,
        ),
        sa.Column(
            "paused_from",
            sa.Enum(
                "QUEUED",
                "SCOPE_VERIFYING",
                "BLOCKED_UNVERIFIED",
                "RECON",
                "AUTH_ESTABLISHING",
                "FAILED_AUTH",
                "CRAWLING",
                "SURFACE_MAPPING",
                "PASSIVE_CHECKS",
                "TESTING",
                "VERIFYING",
                "TRIAGING",
                "REPORTING",
                "COMPLETE",
                "PAUSED",
                "CANCELLED",
                "FAILED",
                name="scanstate",
            ),
            nullable=True,
        ),
        sa.Column("fail_reason", sa.String(length=1000), nullable=True),
        sa.Column("is_degraded", sa.Boolean(), nullable=False),
        sa.Column("degraded_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("llm_token_budget", sa.Integer(), nullable=False),
        sa.Column("llm_tokens_used", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scans_state"), "scans", ["state"], unique=False)
    op.create_index(op.f("ix_scans_target_id"), "scans", ["target_id"], unique=False)
    op.create_table(
        "scope_rules",
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("pattern", sa.String(length=500), nullable=False),
        sa.Column("effect", sa.String(length=10), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scope_rules_target_id"), "scope_rules", ["target_id"], unique=False)
    op.create_table(
        "assets",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("tech_fingerprint", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assets_host"), "assets", ["host"], unique=False)
    op.create_index(op.f("ix_assets_scan_id"), "assets", ["scan_id"], unique=False)
    op.create_table(
        "findings",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("rule_id", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("cwe", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("owasp_top10", sa.String(length=20), nullable=True),
        sa.Column("cvss_vector", sa.String(length=100), nullable=True),
        sa.Column(
            "severity",
            sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO", name="findingseverity"),
            nullable=False,
        ),
        sa.Column(
            "confidence",
            sa.Enum("CONFIRMED", "PROBABLE", "INFORMATIONAL", name="findingconfidence"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "FIXED",
                "REGRESSED",
                "ACCEPTED_RISK",
                "FALSE_POSITIVE",
                name="findingstatus",
            ),
            nullable=False,
        ),
        sa.Column("reproduction", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("narrative", sa.String(length=10000), nullable=False),
        sa.Column("remediation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("first_seen_scan_id", sa.UUID(), nullable=False),
        sa.Column("last_seen_scan_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["first_seen_scan_id"],
            ["scans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_seen_scan_id"],
            ["scans.id"],
        ),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_findings_confidence"), "findings", ["confidence"], unique=False)
    op.create_index(op.f("ix_findings_fingerprint"), "findings", ["fingerprint"], unique=False)
    op.create_index(op.f("ix_findings_rule_id"), "findings", ["rule_id"], unique=False)
    op.create_index(op.f("ix_findings_scan_id"), "findings", ["scan_id"], unique=False)
    op.create_index(op.f("ix_findings_severity"), "findings", ["severity"], unique=False)
    op.create_index(op.f("ix_findings_status"), "findings", ["status"], unique=False)
    op.create_table(
        "reports",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column(
            "format",
            sa.Enum("DASHBOARD", "PDF", "SARIF", "ATTESTATION_LETTER", name="reportformat"),
            nullable=False,
        ),
        sa.Column("storage_pointer", sa.String(length=500), nullable=False),
        sa.Column("verified_by_user_id", sa.UUID(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_scan_id"), "reports", ["scan_id"], unique=False)
    op.create_table(
        "scan_phases",
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column(
            "name",
            sa.Enum(
                "SCOPE_VERIFYING",
                "RECON",
                "AUTH_ESTABLISHING",
                "CRAWLING",
                "SURFACE_MAPPING",
                "PASSIVE_CHECKS",
                "ACTIVE_INJECTION",
                "ACCESS_CONTROL",
                "SESSION_CHECKS",
                "BUSINESS_LOGIC",
                "VERIFYING",
                "TRIAGING",
                "REPORTING",
                name="scanphasename",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "COMPLETED", "FAILED", "SKIPPED", name="phasestatus"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(length=2000), nullable=True),
        sa.Column("stats_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scan_phases_scan_id"), "scan_phases", ["scan_id"], unique=False)
    op.create_table(
        "transcript_records",
        sa.Column("transcript_id", sa.String(length=64), nullable=False),
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("persona_id", sa.UUID(), nullable=True),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("transcript_id"),
    )
    op.create_index(
        op.f("ix_transcript_records_scan_id"), "transcript_records", ["scan_id"], unique=False
    )
    op.create_table(
        "endpoints",
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("path_template", sa.String(length=1000), nullable=False),
        sa.Column(
            "discovered_by_persona_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("discovery_source", sa.String(length=30), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_endpoints_asset_id"), "endpoints", ["asset_id"], unique=False)
    op.create_index(
        op.f("ix_endpoints_path_template"), "endpoints", ["path_template"], unique=False
    )
    op.create_table(
        "evidence",
        sa.Column("finding_id", sa.UUID(), nullable=False),
        sa.Column("transcript_id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("note", sa.String(length=1000), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["transcript_id"],
            ["transcript_records.transcript_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidence_finding_id"), "evidence", ["finding_id"], unique=False)
    op.create_table(
        "verifications",
        sa.Column("finding_id", sa.UUID(), nullable=False),
        sa.Column("reproduced_count", sa.Integer(), nullable=False),
        sa.Column("attempted_count", sa.Integer(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["finding_id"], ["findings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verifications_finding_id"), "verifications", ["finding_id"], unique=True
    )
    op.create_table(
        "parameters",
        sa.Column("endpoint_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("location", sa.String(length=20), nullable=False),
        sa.Column("semantic_label", sa.String(length=50), nullable=True),
        sa.Column("label_confidence", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_parameters_endpoint_id"), "parameters", ["endpoint_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parameters_endpoint_id"), table_name="parameters")
    op.drop_table("parameters")
    op.drop_index(op.f("ix_verifications_finding_id"), table_name="verifications")
    op.drop_table("verifications")
    op.drop_index(op.f("ix_evidence_finding_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_endpoints_path_template"), table_name="endpoints")
    op.drop_index(op.f("ix_endpoints_asset_id"), table_name="endpoints")
    op.drop_table("endpoints")
    op.drop_index(op.f("ix_transcript_records_scan_id"), table_name="transcript_records")
    op.drop_table("transcript_records")
    op.drop_index(op.f("ix_scan_phases_scan_id"), table_name="scan_phases")
    op.drop_table("scan_phases")
    op.drop_index(op.f("ix_reports_scan_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_findings_status"), table_name="findings")
    op.drop_index(op.f("ix_findings_severity"), table_name="findings")
    op.drop_index(op.f("ix_findings_scan_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_rule_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_fingerprint"), table_name="findings")
    op.drop_index(op.f("ix_findings_confidence"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_assets_scan_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_host"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_scope_rules_target_id"), table_name="scope_rules")
    op.drop_table("scope_rules")
    op.drop_index(op.f("ix_scans_target_id"), table_name="scans")
    op.drop_index(op.f("ix_scans_state"), table_name="scans")
    op.drop_table("scans")
    op.drop_index(op.f("ix_scan_policies_target_id"), table_name="scan_policies")
    op.drop_table("scan_policies")
    op.drop_index(op.f("ix_personas_tenant_key"), table_name="personas")
    op.drop_index(op.f("ix_personas_target_id"), table_name="personas")
    op.drop_table("personas")
    op.drop_index(op.f("ix_targets_root_domain"), table_name="targets")
    op.drop_index(op.f("ix_targets_organization_id"), table_name="targets")
    op.drop_table("targets")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_index(op.f("ix_users_clerk_user_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_table("credentials")
    # ### end Alembic commands ###

    # Alembic's autogenerate does not emit DROP TYPE for Postgres ENUMs on
    # downgrade (a table's sa.Enum column doesn't own the type — several
    # tables could share it), so it has to be explicit here or a downgrade
    # followed by a re-upgrade fails with "type already exists".
    bind = op.get_bind()
    for enum_name in (
        "credentialkind",
        "orgrole",
        "ownershipverificationmethod",
        "loginstrategy",
        "scanintensity",
        "scanstate",
        "scanphasename",
        "phasestatus",
        "findingseverity",
        "findingconfidence",
        "findingstatus",
        "reportformat",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
