"""persona/credential timestamps timezone-aware

Revision ID: 80afad442615
Revises: c240c2157e8a
Create Date: 2026-09-16 06:50:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "80afad442615"
down_revision: str | None = "c240c2157e8a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Hand-written, not autogenerated (see c240c2157e8a for the same practice):
# these three columns were declared without DateTime(timezone=True), unlike
# every other timestamp column in the schema (TimestampMixin,
# Verification.last_run_at, Target.ownership_verified_at, ...). It went
# unnoticed because a single-row UPDATE tolerates the mismatch; a batched
# UPDATE across multiple Persona rows in one flush does not (asyncpg:
# "can't subtract offset-naive and offset-aware datetimes") — found while
# wiring AUTH_ESTABLISHING for more than one persona at once (M2 slice 1).
# `USING` casts are safe no-op reinterpretations here: every existing value
# was always produced by `datetime.now(UTC)`, so treating the stored
# instant as UTC is exactly correct, not a guess.


def upgrade() -> None:
    op.execute(
        "ALTER TABLE credentials ALTER COLUMN revoked_at TYPE TIMESTAMP WITH TIME ZONE "
        "USING revoked_at AT TIME ZONE 'UTC'"
    )
    op.execute(
        "ALTER TABLE personas ALTER COLUMN session_state_updated_at TYPE TIMESTAMP WITH TIME ZONE "
        "USING session_state_updated_at AT TIME ZONE 'UTC'"
    )
    op.execute(
        "ALTER TABLE personas ALTER COLUMN session_state_expires_at TYPE TIMESTAMP WITH TIME ZONE "
        "USING session_state_expires_at AT TIME ZONE 'UTC'"
    )


def downgrade() -> None:
    op.alter_column(
        "personas",
        "session_state_expires_at",
        type_=sa.DateTime(timezone=False),
    )
    op.alter_column(
        "personas",
        "session_state_updated_at",
        type_=sa.DateTime(timezone=False),
    )
    op.alter_column(
        "credentials",
        "revoked_at",
        type_=sa.DateTime(timezone=False),
    )
