"""add recon fields to asset

Revision ID: c240c2157e8a
Revises: 59e49f2ddeda
Create Date: 2026-09-15 16:18:12.554562

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c240c2157e8a"
down_revision: str | None = "59e49f2ddeda"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand (not autogenerated): these columns are
    # NOT NULL, so any pre-existing `assets` rows need a backfill value, not
    # just a Python-side ORM default that only applies to new inserts.
    op.add_column(
        "assets",
        sa.Column(
            "ip_addresses",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
    )
    op.add_column(
        "assets",
        sa.Column(
            "http_probes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
    )
    op.add_column(
        "assets",
        sa.Column(
            "discovery_source",
            sa.String(length=30),
            nullable=False,
            server_default="root_domain",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assets", "discovery_source")
    op.drop_column("assets", "http_probes")
    op.drop_column("assets", "ip_addresses")
    # ### end Alembic commands ###
